#!/usr/bin/env python3
"""Assert charts/k8s-buddy/templates/clusterrole.yaml's rendered `rules:`
match config/rbac/role.yaml's exactly.

config/rbac/role.yaml is generated by `make manifests` from
internal/controller/plant_controller.go's +kubebuilder:rbac markers, and the
`lint` CI job already gates that generation against drift (`make manifests
generate && git diff --exit-code config/ api/`). The chart's ClusterRole is a
Helm template, not a generated artifact, so a marker change has no automatic
way to reach it -- this script is that gate's counterpart for the chart: it
renders the chart's ClusterRole with `helm template` and fails loudly if its
`rules:` (compared as a set, independent of ordering) has drifted from
config/rbac/role.yaml's own rules.

Usage: helm template <release> charts/k8s-buddy --show-only templates/clusterrole.yaml > <path>
       python3 hack/check-helm-rbac-drift.py <path>
"""

import sys

import yaml


def load_cluster_role_rules(path):
    with open(path, encoding="utf-8") as f:
        docs = list(yaml.safe_load_all(f))
    for doc in docs:
        if doc and doc.get("kind") == "ClusterRole":
            return doc.get("rules", [])
    raise SystemExit(f"no ClusterRole document found in {path}")


def normalize(rules):
    normalized = []
    for rule in rules:
        normalized.append(
            {key: sorted(value) if isinstance(value, list) else value for key, value in rule.items()}
        )
    return sorted(
        normalized,
        key=lambda r: (sorted(r.get("apiGroups", [])), sorted(r.get("resources", []))),
    )


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <rendered-clusterrole.yaml>", file=sys.stderr)
        return 2

    chart_rules = normalize(load_cluster_role_rules(sys.argv[1]))
    source_rules = normalize(load_cluster_role_rules("config/rbac/role.yaml"))

    if chart_rules != source_rules:
        print(
            "DRIFT: charts/k8s-buddy/templates/clusterrole.yaml's rules no longer "
            "match config/rbac/role.yaml. If you just edited a +kubebuilder:rbac "
            "marker, run `make manifests` and mirror the resulting "
            "config/rbac/role.yaml rules into templates/clusterrole.yaml by hand.",
            file=sys.stderr,
        )
        print(f"chart rules:  {chart_rules}", file=sys.stderr)
        print(f"source rules: {source_rules}", file=sys.stderr)
        return 1

    print("confirmed: charts/k8s-buddy's ClusterRole rules match config/rbac/role.yaml exactly")
    return 0


if __name__ == "__main__":
    sys.exit(main())
