#!/usr/bin/env python3
"""Assert charts/k8s-buddy's MutatingWebhookConfiguration and
ValidatingWebhookConfiguration templates match config/webhook/manifests.yaml
on every field that isn't legitimately install-scoped.

config/webhook/manifests.yaml is generated by `make manifests` from
api/v1alpha1/plant_webhook.go's own +kubebuilder:webhook markers, and the
`lint` CI job already gates that generation against drift (`make manifests
generate && git diff --exit-code config/ api/`). The chart's two webhook
configuration templates are hand-written Helm templates, not generated
artifacts, so a marker change (a new rule, a different failurePolicy, a
timeout change, ...) has no automatic way to reach them -- this script is
that gate's counterpart, the same role hack/check-helm-rbac-drift.py already
plays for the ClusterRole.

Compared exactly, per webhook entry: `name`, `rules`, `failurePolicy`,
`sideEffects`, `timeoutSeconds`, `admissionReviewVersions`. Deliberately NOT
compared: the object's own `metadata.name` and `clientConfig` -- both are
release-scoped in the chart (`{{ include "k8s-buddy.fullname" . }}-...`) and
fixed in config/webhook/manifests.yaml (the kustomize path's
"plant-operator-*" names and clientConfig.service), by design, the same way
hack/check-helm-rbac-drift.py excuses `resourceNames` for the identical
reason.

Usage: helm template <release> charts/k8s-buddy \
           --show-only templates/mutatingwebhookconfiguration.yaml \
           --show-only templates/validatingwebhookconfiguration.yaml \
           > <path>
       python3 hack/check-helm-webhook-drift.py <path>
"""

import sys

import yaml

COMPARED_FIELDS = ["name", "rules", "failurePolicy", "sideEffects", "timeoutSeconds", "admissionReviewVersions"]

WEBHOOK_KINDS = ("MutatingWebhookConfiguration", "ValidatingWebhookConfiguration")


def load_docs(path):
    with open(path, encoding="utf-8") as f:
        return [d for d in yaml.safe_load_all(f) if d]


def find_by_kind(docs, kind, source_label):
    for d in docs:
        if d.get("kind") == kind:
            return d
    raise SystemExit(f"no {kind} document found in {source_label}")


def normalize(entry):
    normalized = {}
    for key in COMPARED_FIELDS:
        value = entry.get(key)
        if isinstance(value, list) and value and isinstance(value[0], dict):
            # `rules` -- a list of rule objects. Sort each rule's own list
            # fields, then sort the list of rules, so ordering never causes
            # a false positive.
            value = sorted(
                (
                    {k: sorted(v) if isinstance(v, list) else v for k, v in rule.items()}
                    for rule in value
                ),
                key=lambda r: str(sorted(r.items())),
            )
        elif isinstance(value, list):
            value = sorted(value)
        normalized[key] = value
    return normalized


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <rendered-chart-webhook-configs.yaml>", file=sys.stderr)
        return 2

    chart_docs = load_docs(sys.argv[1])
    source_docs = load_docs("config/webhook/manifests.yaml")

    problems = []
    for kind in WEBHOOK_KINDS:
        chart_doc = find_by_kind(chart_docs, kind, sys.argv[1])
        source_doc = find_by_kind(source_docs, kind, "config/webhook/manifests.yaml")

        chart_webhooks = chart_doc.get("webhooks", [])
        source_webhooks = source_doc.get("webhooks", [])
        if len(chart_webhooks) != len(source_webhooks):
            problems.append(
                f"{kind}: chart has {len(chart_webhooks)} webhook entries, "
                f"source has {len(source_webhooks)}"
            )
            continue

        chart_entry = normalize(chart_webhooks[0])
        source_entry = normalize(source_webhooks[0])
        if chart_entry != source_entry:
            problems.append(f"{kind}: chart={chart_entry} source={source_entry}")

    if problems:
        print(
            "DRIFT: charts/k8s-buddy's webhook configuration templates no longer match "
            "config/webhook/manifests.yaml. If you just edited a +kubebuilder:webhook "
            "marker on api/v1alpha1/plant_webhook.go, run `make manifests` and mirror the "
            "resulting config/webhook/manifests.yaml's rules/failurePolicy/sideEffects/"
            "timeoutSeconds/admissionReviewVersions into "
            "charts/k8s-buddy/templates/{mutating,validating}webhookconfiguration.yaml by hand.",
            file=sys.stderr,
        )
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    print(
        "confirmed: charts/k8s-buddy's webhook configuration templates match "
        "config/webhook/manifests.yaml exactly (except metadata.name/clientConfig, "
        "which are deliberately install-scoped)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
