#!/usr/bin/env python3
"""Assert charts/k8s-buddy/templates/clusterrole.yaml's rendered `rules:`
match config/rbac/role.yaml's exactly, EXCEPT for `resourceNames`, which is
checked for presence/count rather than exact value (see below).

config/rbac/role.yaml is generated by `make manifests` from
internal/controller/plant_controller.go's +kubebuilder:rbac markers, and the
`lint` CI job already gates that generation against drift (`make manifests
generate && git diff --exit-code config/ api/`). The chart's ClusterRole is a
Helm template, not a generated artifact, so a marker change has no automatic
way to reach it -- this script is that gate's counterpart for the chart: it
renders the chart's ClusterRole with `helm template` and fails loudly if its
`rules:` (compared as a set, independent of ordering) has drifted from
config/rbac/role.yaml's own rules.

`resourceNames` is a deliberate, narrow exception. One rule in this
ClusterRole (admissionregistration.k8s.io, for cmd/plant-operator's webhook
caBundle-patching bootstrap -- see docs/adr/0009-webhook-certificate-strategy
.md) is scoped with resourceNames pinned to this project's two
MutatingWebhookConfiguration/ValidatingWebhookConfiguration objects. Those
names are RELEASE-SCOPED in the chart (`{{ include "k8s-buddy.fullname" . }}
-mutating-webhook-configuration`, following the same release-scoping every
other cluster-scoped object name in this chart already uses -- see
clusterrole.yaml's own metadata.name) but FIXED in config/rbac/role.yaml
(the kustomize path's "plant-operator-*" names, which controller-gen's
+kubebuilder:webhookconfiguration markers bake in literally). A byte-for-byte
comparison of resourceNames would therefore report drift on every single
render, for a difference that is by design, not a regression -- so this
script normalizes resourceNames out of the primary equality check, but keeps
a second, explicit assertion (assert_resource_names_present below) that
whichever rules DO carry resourceNames on one side also carry a same-COUNT,
non-empty resourceNames list on the other: the actual regression this drops
protection against -- a rule silently losing its narrowing altogether, going
from "these two named objects only" to "every object of this type" -- is
still caught.

Usage: helm template <release> charts/k8s-buddy --show-only templates/clusterrole.yaml > <path>
       python3 hack/check-helm-rbac-drift.py <path>
"""

import sys

import yaml


def load_cluster_role_rules(path):
    with open(path, encoding="utf-8") as f:
        docs = list(yaml.safe_load_all(f))
    for doc in docs:
        if doc and doc.get("kind") == "ClusterRole":
            return doc.get("rules", [])
    raise SystemExit(f"no ClusterRole document found in {path}")


def rule_key(rule):
    return (tuple(sorted(rule.get("apiGroups", []))), tuple(sorted(rule.get("resources", []))))


def normalize(rules):
    normalized = []
    for rule in rules:
        entry = {
            key: sorted(value) if isinstance(value, list) else value
            for key, value in rule.items()
            if key != "resourceNames"
        }
        normalized.append(entry)
    return sorted(normalized, key=lambda r: (sorted(r.get("apiGroups", [])), sorted(r.get("resources", []))))


def assert_resource_names_present(chart_rules, source_rules):
    """For every rule (matched by apiGroups+resources) that carries
    resourceNames on either side, assert both sides carry a non-empty
    resourceNames list of the SAME LENGTH -- the exact values are expected to
    differ (release-scoped vs. fixed), but a rule silently losing its
    resourceNames narrowing entirely (on either side) is still a real
    regression this must catch.
    """
    chart_by_key = {rule_key(r): r for r in chart_rules}
    source_by_key = {rule_key(r): r for r in source_rules}

    problems = []
    for key in set(chart_by_key) | set(source_by_key):
        chart_names = chart_by_key.get(key, {}).get("resourceNames")
        source_names = source_by_key.get(key, {}).get("resourceNames")
        if not chart_names and not source_names:
            continue
        if not chart_names or not source_names:
            problems.append(
                f"rule {key}: resourceNames present on one side only "
                f"(chart={chart_names!r}, source={source_names!r})"
            )
        elif len(chart_names) != len(source_names):
            problems.append(
                f"rule {key}: resourceNames count differs "
                f"(chart has {len(chart_names)}, source has {len(source_names)})"
            )
    return problems


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <rendered-clusterrole.yaml>", file=sys.stderr)
        return 2

    chart_rules_raw = load_cluster_role_rules(sys.argv[1])
    source_rules_raw = load_cluster_role_rules("config/rbac/role.yaml")

    resource_name_problems = assert_resource_names_present(chart_rules_raw, source_rules_raw)
    if resource_name_problems:
        print("DRIFT: resourceNames narrowing does not match between chart and source:", file=sys.stderr)
        for p in resource_name_problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    chart_rules = normalize(chart_rules_raw)
    source_rules = normalize(source_rules_raw)

    if chart_rules != source_rules:
        print(
            "DRIFT: charts/k8s-buddy/templates/clusterrole.yaml's rules no longer "
            "match config/rbac/role.yaml (ignoring resourceNames values, see this "
            "script's own header comment). If you just edited a +kubebuilder:rbac "
            "marker, run `make manifests` and mirror the resulting "
            "config/rbac/role.yaml rules into templates/clusterrole.yaml by hand.",
            file=sys.stderr,
        )
        print(f"chart rules:  {chart_rules}", file=sys.stderr)
        print(f"source rules: {source_rules}", file=sys.stderr)
        return 1

    print("confirmed: charts/k8s-buddy's ClusterRole rules match config/rbac/role.yaml "
          "exactly (except resourceNames values, which are checked for presence/count only)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
