apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-buddy

resources:
  - ../base/namespace.yaml
  - ../base/buddy-api-deployment.yaml
  - ../base/buddy-worker-deployment.yaml
  - ../base/chaos-buddy-deployment.yaml
  - ../base/service.yaml
  - ../base/pdb.yaml
  - ../base/networkpolicy.yaml
  - ../base/configmap.yaml

images:
  - name: buddy-api
    newTag: latest
  - name: buddy-worker
    newTag: latest
  - name: chaos-buddy
    newTag: latest

replicas:
  - name: buddy-api
    count: 2
  - name: buddy-worker
    count: 1
  - name: chaos-buddy
    count: 1
